version: "3.1"
# lancer avec : docker-compose --env-file .env up
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql-data:/var/lib/mysql
      #- ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
  adminer:
    container_name: adminer
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: "${ADMINER_DEFAULT_SERVER}"
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  mysql-data:
